SYSTEM:
  NUM_GPUS: 1
  NUM_CPUS: 8
AUGMENTOR:
  SMOOTH: false
  ROTATE:
    ENABLED: true
  FLIP:
    ENABLED: true
  RESCALE:
    ENABLED: false
  ELASTIC:
    ENABLED: false
  GRAYSCALE:
    ENABLED: false
  MISSINGPARTS:
    ENABLED: false
  MISSINGSECTION:
    ENABLED: false
  MISALIGNMENT:
    ENABLED: false
  MOTIONBLUR:
    ENABLED: false
  CUTBLUR:
    ENABLED: false
  CUTNOISE:
    ENABLED: true
    P: 0.3
MODEL:
  ARCHITECTURE: unet_3d
  BLOCK_TYPE: residual_se
  INPUT_SIZE:
  - 192
  - 192
  - 192
  OUTPUT_SIZE:
  - 192
  - 192
  - 192
  IN_PLANES: 1
  OUT_PLANES: 1
  TARGET_OPT:
  - '0'
  LOSS_OPTION:
  - - WeightedBCEWithLogitsLoss
    - DiceLoss
  LOSS_WEIGHT:
  - - 1.0
    - 1.0
  WEIGHT_OPT:
  - - '1'
    - '0'
  OUTPUT_ACT:
  - - none
    - sigmoid
DATASET:
  IMAGE_NAME: /gpfs/radev/home/yf354/marmoset_data/bouton_train_images.txt
  LABEL_NAME: /gpfs/radev/home/yf354/marmoset_data/bouton_train_labels.txt
  INPUT_PATH: /gpfs/radev/home/yf354/pytorch_connectomics/datasets/Lucchi/
  OUTPUT_PATH: outputs/Marmoset/bouton/isotropic_v2
  IS_ISOTROPIC: true
  PAD_SIZE:
  - 48
  - 48
  - 48
SOLVER:
  ITERATION_RESTART: true
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.0001
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 70000
  SAMPLES_PER_BATCH: 2
MONITOR:
  ITERATION_NUM:
  - 200
  - 1000
INFERENCE:
  INPUT_SIZE:
  - 192
  - 192
  - 192
  OUTPUT_SIZE:
  - 192
  - 192
  - 192
  OUTPUT_ACT:
  - sigmoid
  IMAGE_NAME: precomputed://file:///gpfs/marilyn/pi/kuan/shared/marmoset_project/precomputed_outputs/Gaussian-aligned_FIBSEM_Basil_OML_of_DG
  OUTPUT_PATH: precomputed://file:///gpfs/marilyn/pi/kuan/shared/marmoset_project/precomputed_outputs/fib_b_inference_bouton_v2
  OUTPUT_NAME: result.h5
  PAD_SIZE:
  - 48
  - 48
  - 48
  AUG_MODE: min
  AUG_NUM: None
  STRIDE:
  - 96
  - 96
  - 96
  SAMPLES_PER_BATCH: 16
  GEOMETRY:
    CORE_SIZE: 512
    HALO: 32
    OUTPUT_CHUNK_SIZE: 128
    MIP: 0
